app:
  port: 14567
  regionDynamoDB: dump
  endpointDynamoDB: http://example.com
  test: false

  # article
  articleResource: https://shashki.online:8443/article/api/v1/article
  articlesResource: https://shashki.online:8443/article/api/v1/articles

  # board
  boardboxResource: https://shashki.online:8443/board/api/v1/board

  # security
  registerResource: https://shashki.online:8443/security/api/v1/register
  authorizeResource: https://shashki.online:8443/security/api/v1/authorize
  authenticateResource: https://shashki.online:8443/security/api/v1/authenticate
  userInfoResource: https://shashki.online:8443/security/api/v1/user-info
  logoutResource: https://shashki.online:8443/security/api/v1/logout
