app:
  port: 14567
  regionDynamoDB: dump
  endpointDynamoDB: http://example.com
  test: false
  articleResource: https://a24v4rzc10.execute-api.eu-west-1.amazonaws.com/dev/api/v1/article
  articlesResource: https://a24v4rzc10.execute-api.eu-west-1.amazonaws.com/dev/api/v1/articles

  boardboxResource: https://9l3rwmrob7.execute-api.eu-west-1.amazonaws.com/dev/api/v1/board

  registerResource: https://fwkmo7eyx5.execute-api.eu-west-1.amazonaws.com/dev/api/v1/register
  authorizeResource: https://fwkmo7eyx5.execute-api.eu-west-1.amazonaws.com/dev/api/v1/authorize
  authenticateResource: https://fwkmo7eyx5.execute-api.eu-west-1.amazonaws.com/dev/api/v1/authenticate
  userInfoResource: https://fwkmo7eyx5.execute-api.eu-west-1.amazonaws.com/dev/api/v1/user-info
  logoutResource: https://fwkmo7eyx5.execute-api.eu-west-1.amazonaws.com/dev/api/v1/logout
