image: keeganwitt/docker-gradle-root

stages:
  - production

job_production:
  stage: production
  tags:
      - shashki-back
  script:
    - TOMCATUID=112
    - TOMCATUSER=tomcat8
    - useradd -u $TOMCATUID -ms /bin/bash $TOMCATUSER
    - mkdir -p /var/lib/tomcat8/webapps/{article,board,security}
    - gradle clean build deploylocal
  only:
    - tags
