stages:
  - production

job_production:
  stage: production
  tags:
      - shashki-back
  script:
    - sudo chmod -R g+w /var/lib/tomcat8/webapps
    - /root/.sdkman/candidates/gradle/current/bin/gradle clean build deploylocal --stacktrace

variables:
  CFG4J_ENV: prod
