stages:
- production

job_production:
  stage: prod
  tags:
  - shashki-back
  script:
  - rm -rf /opt/tomcat/webapps/{article*,board*,security*}
  - systemctl stop apache-tomcat
  - ./gradlew clean build deploylocal --stacktrace
  - chown -R tomcat:tomcat /opt/tomcat/webapps
  - systemctl start apache-tomcat

variables:
  CFG4J_ENV: prod
