stages:
  - production

job_production:
  stage: production
  tags:
      - shashki-back
  script:
    - rm -rf /var/lib/tomcat8/webapps/{article*,board*,security*}
    - service tomcat8 stop
    - ./gradlew clean build deploylocal --stacktrace
    - chown -R tomcat8:tomcat8 /var/lib/tomcat8/webapps
    - service tomcat8 start

variables:
  CFG4J_ENV: prod