stages:
- production

job_production:
  stage: production
  tags:
  - shashki-back
  script:
  - whoami
  - rm -rf /opt/tomcat/webapps/{article*,board*,security*}
  #  - systemctl stop apache-tomcat
  - ./gradlew clean build deploylocal --stacktrace
  - sudo chown -R tomcat:tomcat /opt/tomcat/webapps
#  - systemctl start apache-tomcat

variables:
  CFG4J_ENV: prod
