image: gradle:jdk10

stages:
  - production

job_production:
  stage: production
  tags:
      - shashki-back
  script:
    - TOMCATUID=112
    - TOMCATUSER=tomcat8
    - sudo -u root useradd -u $TOMCATUID -ms /bin/bash $TOMCATUSER
    - sudo -u mkdir -p /var/lib/tomcat8/webapps/{article,board,security}
    - gradle clean build deploylocal
variables:
  GIT_SSL_NO_VERIFY: "true"
