stages:
  - production

job_production:
  stage: production
  tags:
      - shashki-back
  script:
    - whoami
    - ./gradlew clean build deploylocal --stacktrace

#variables:
#  GIT_SSL_NO_VERIFY: "true"
