stages:
  - production

job_production:
  stage: production
  tags:
      - shashki-back
  script:
    - sudo chmod -R g+w /var/lib/tomcat8/webapps
    - ./gradlew clean build deploylocal --stacktrace

variables:
  CFG4J_ENV: prod
