production:
  stage: deploy
  script:
    - TOMCATUID=112
    - TOMCATUSER=tomcat8
    - useradd -u $TOMCATUID -ms /bin/bash $TOMCATUSER
    - mkdir -p /var/lib/tomcat8/webapps/{article,board,security}
    - gradle clean build deploylocal

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
