stages:
  - production

job_production:
  stage: production
  tags:
      - shashki-back
  script:
    - ./gradlew clean build deploylocal --stacktrace
    - chown -R tomcat8:tomcat8 /var/lib/tomcat8/webapps
    - services tomcat8 restart

variables:
  CFG4J_ENV: prod
