app:
  port: 14567
  regionDynamoDB: eu-west-1
  endpointDynamoDB: http://localhost:8081
  test: true
  headers: requested-api,api-article,x-api-key,content-type,sign,sign-request,user-session,access-token,access-control-allow-credentials
  methods: GET,POST,PUT,OPTIONS,HEADER,DELETE
  origin: http://localhost:4200

  boardboxResource: http://localhost:24567/api/v1/board
  registerResource: http://localhost:34567/api/security/register
  authorizeResource: http://localhost:34567/api/security/authorize
  authenticateResource: http://localhost:34567/api/security/authenticate

  articlesFetchLimit: 50
