app:
  port: 14567
  regionDynamoDB: eu-west-1
  endpointDynamoDB: http://localhost:8081
  test: true
  headers: requested-api,api-article,x-api-key,content-type,sign,sign-request,access-control-allow-credentials
  methods: GET,POST,PUT,OPTIONS,HEADER,DELETE
  origin: http://localhost:4200
  boardResource: http://localhost:24567/api/v1/board
  articlesFetchLimit: 50
  encodeTokenKey: 123