app:
  port: 34567
  regionDynamoDB: eu-west-1
  endpointDynamoDB: http://localhost:8765
  local: true
  headers: requested-api,api-article,x-api-key,content-type,sign,sign-request,user-session,anonymous-session,user-id,email,access-token,user-authorities,access-control-allow-credentials
  methods: GET,POST,PUT,OPTIONS,HEADER,DELETE
  origin: http://shashki.local # localhost
  sessionLength: 20
  tokenLength: 20
  superHashEnvName: SHASHKI_SUPER_USER
  passwordFileKey: yGqa2Ga3wCqVb65U
  passwordFilename: /Users/aleksey/Development/shashki/shashkiSpark/dynamodb-local/shashki_online/ShashkiUsers.pwd

  domain: shashki.online
  cost: 10000
  sysSigma: V>K0!PW`ojeK_'9"~R1;s(!Fx6PnOabc
  misc: 8