# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: articleservice

provider:
  name: aws
  runtime: java8
  timeout: 300
  memorySize: 256

  stage: dev
  region: eu-west-1

  apiKeys:
    - ARTICLE_API_KEY

# define service wide environment variables here
  environment:
    CFG4J_ENV: prod

# packaging information here
package:
  artifact: build/distributions/articleservice-1.0.zip

functions:
  article:
    handler: com.workingbit.article.LambdaHandler::handleRequest

    events:
      - http:
          path: /api/v1/articles
          method: get
      - http:
          path: /api/v1/articles
          method: options
      - http:
          path: /api/v1/article/{article}
          method: get
          request:
            parameters:
              path:
                articleId: true
      - http:
          path: /api/v1/article/{article}
          method: options
          request:
            parameters:
              path:
                articleId: true
      - http:
          path: /api/v1/article/{article}/board
          method: get
          request:
            parameters:
              path:
                articleId: true
      - http:
          path: /api/v1/article/{article}/board
          method: options
          request:
            parameters:
              path:
                articleId: true
      - http:
          path: /api/v1/article
          method: post
      - http:
          path: /api/v1/article
          method: put
      - http:
          path: /api/v1/article
          method: options

#resources:
#  Resources:
#    DynamoDbTableArticle:
#      Type: AWS::DynamoDB::Table
#      Properties:
#        TableName: Article
#        AttributeDefinitions:
#          - AttributeName: id
#            AttributeType: S
#          - AttributeName: createdAt
#            AttributeType: S
#        KeySchema:
#          - AttributeName: id
#            KeyType: HASH
#          - AttributeName: createdAt
#            KeyType: RANGE
#        ProvisionedThroughput:
#          ReadCapacityUnits: 1
#          WriteCapacityUnits: 1
#        GlobalSecondaryIndexes:
#        - IndexName: articleIndex
#          KeySchema:
#          - AttributeName: id
#            KeyType: HASH
#          - AttributeName: createdAt
#            KeyType: RANGE
#          Projection:
#            ProjectionType: ALL
#          ProvisionedThroughput:
#            ReadCapacityUnits: 1
#            WriteCapacityUnits: 1
#    DynamoDBIamPolicyArticle:
#      Type: AWS::IAM::Policy
#      DependsOn: DynamoDbTableArticle
#      Properties:
#        PolicyName: lambda-dynamodb-article
#        PolicyDocument:
#          Version: '2012-10-17'
#          Statement:
#            - Effect: Allow
#              Action:
#                - dynamodb:DescribeTable
#                - dynamodb:GetItem
#                - dynamodb:PutItem
#                - dynamodb:UpdateItem
#                - dynamodb:Scan
#                - dynamodb:Query
#              Resource: arn:aws:dynamodb:*:*:table/Article
#        Roles:
#          - Ref: IamRoleLambdaExecution
#
#plugins:
#  - serverless-dynamodb-local
##  - serverless-dynamodb-fixtures-plugin
#
#custom:
#  dynamodb:
#    start:
#      port: 8081
#      inMemory: true
#      migrate: true
