app:
  port: 14567
  regionDynamoDB: eu-west-1
  test: true
  articleResource: http://localhost:8001/article/api/v1/article
  articlesResource: http://localhost:8001/article/api/v1/articles
  boardboxResource: http://localhost:8002/board/api/v1/board
  registerResource: http://localhost:8003/security/api/v1/register
  authorizeResource: http://localhost:8003/security/api/v1/security/authorize
  authenticateResource: http://localhost:8003/security/api/v1/authenticate
  userInfoResource: http://localhost:8003/security/api/v1/user-info
  logoutResource: http://localhost:8003/security/api/v1/logout
