app:
  port: 14567
  regionDynamoDB: eu-west-1
  test: true
  articleResource: http://localhost:14567/api/v1/article
  articlesResource: http://localhost:14567/api/v1/articles
  boardboxResource: http://localhost:24567/api/v1/board
  registerResource: http://localhost:34567/api/security/register
  authorizeResource: http://localhost:34567/api/security/authorize
  authenticateResource: http://localhost:34567/api/security/authenticate
  userInfoResource: http://localhost:34567/api/security/user-info
  logoutResource: http://localhost:34567/api/security/logout

