app:
  port: 14567
  regionDynamoDB: eu-west-1
  endpointDynamoDB: http://localhost:8765
  local: true

  # article
#  articleResource: https://localhost:8888/////article/api/v1/article
#  articlesResource: https://localhost:8888/////article/api/v1/articles
#
#  # board
#  boardboxResource: https://localhost:8888/////board/api/v1/board
#  parsePdnResource: https://localhost:8888/////board/api/v1/parse-pdn
#
#  # security
#  registerResource: https://localhost:8888/////security/api/v1/register
#  authorizeResource: https://localhost:8888/////security/api/v1/authorize
#  authenticateResource: https://localhost:8888/////security/api/v1/authenticate
#  userInfoResource: https://localhost:8888/////security/api/v1/user-info
#  saveUserInfoResource: https://localhost:8888/////security/api/v1/save-user-info
#  logoutResource: https://localhost:8888/////security/api/v1/logout

  preRegisterResource: https://localhost:8888/article/api/v1/pre-register
  preAuthorizeResource: https://localhost:8888/article/api/v1/pre-authorize
  articleResource: https://localhost:8888/article/api/v1/article
  articlesResource: https://localhost:8888/article/api/v1/articles
  boardboxResource: https://localhost:8888/board/api/v1/board
  boardboxDeleteByArticleIdResource: https://localhost:8888/board/api/v1/board-delete-by-article-id
  parsePdnResource: https://localhost:8888/board/api/v1/parse-pdn
  registerResource: https://localhost:8888/security/api/v1/register
  authorizeResource: https://localhost:8888/security/api/v1/authorize
  remindPasswordResource: https://localhost:8888/security/api/v1/remind-passwordHash
  authenticateResource: https://localhost:8888/security/api/v1/authenticate
  userInfoResource: https://localhost:8888/security/api/v1/user-info
  saveUserInfoResource: https://localhost:8888/security/api/v1/save-user-info
  logoutResource: https://localhost:8888/security/api/v1/logout

  redisHost: 127.0.0.1
  redisPort: 6379
