app:
  port: 14567
  regionDynamoDB: dump
  endpointDynamoDB: http://example.com
  test: false
  headers: requested-api,api-article,x-api-key,content-type,sign,sign-request,access-control-allow-credentials
  #,0,1,10,11,12,13,14,15,16,17,18,19,2,20,21,22,23,24,25,26,27,28,29,3,30,31,32,33,34,35,36,37,38,39,4,40,41,42,43,44,45,46,47,48,49,5,50,51,52,53,54,55,56,57,58,59,6,60,61,62,63,64,7,8,9
  methods: GET,POST,PUT,OPTIONS,HEADER,DELETE
  origin: https://wiki.shashki.online
  boardResource: https://8vc9rklqxh.execute-api.eu-west-1.amazonaws.com/dev/api/v1/board
  articlesFetchLimit: 50
