app:
  regionDynamoDB: dump
  endpointDynamoDB: http://example.com
  test: false
  headers: Content-Type
  methods: GET,POST,PUT,OPTIONS,HEADER,DELETE
  origin: https://wiki.shashki.online
  boardResource: https://8vc9rklqxh.execute-api.eu-west-1.amazonaws.com/dev/api/v1
  articlesFetchLimit: 50
