app:
  port: 14567
  regionDynamoDB: eu-west-1
  local: true
  articleResource: http://localhost:8888/article/api/v1/article
  articlesResource: http://localhost:8888/article/api/v1/articles
  boardboxResource: http://localhost:8888/board/api/v1/board
  boardboxDeleteByArticleIdResource: http://localhost:8888/board/api/v1/board-delete-by-article-id
  parsePdnResource: http://localhost:8888/board/api/v1/parse-pdn
  preRegisterResource: http://localhost:8888/security/api/v1/pre-register
  preAuthorizeResource: http://localhost:8888/security/api/v1/pre-authorize
  registerResource: http://localhost:8888/security/api/v1/register
  authorizeResource: http://localhost:8888/security/api/v1/authorize
  remindPasswordResource: http://localhost:8888/security/api/v1/remind-passwordHash
  authenticateResource: http://localhost:8888/security/api/v1/authenticate
  userInfoResource: http://localhost:8888/security/api/v1/user-info
  saveUserInfoResource: http://localhost:8888/security/api/v1/save-user-info
  logoutResource: http://localhost:8888/security/api/v1/logout

  redisHost: 127.0.0.1
  redisPort: 6379
